# Generated by Django 3.0.2 on 2020-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth',
            field=models.DateField(default='01.01.1970'),
        ),
    ]
