# Generated by Django 3.0.2 on 2020-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='static/images/clients/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
